apiVersion: v1
kind: Pod
metadata:
  name: pod-ml
  labels:
    name: pod-ml
spec:
  volumes:
    - name: site-data
      persistentVolumeClaim:
      claimName: pvc-nfs-mlo
    - hostPath:
      path: /usr/lib/nvidia-375/bin
      name: bin
    - hostPath:
      path: /usr/lib/nvidia-375
      name: lib
  containers:
    - name:  ml
      image: ntxvm015.iccluster.epfl.ch/mlo/ml_prod:1.0
      resources:
        limits:
          alpha.kubernetes.io/nvidia-gpu: 2
      ports:
        - containerPort: 8888
          name: notebook
        - containerPort: 6006
          name: tensorboard
      volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /mlodata1
          name: site-data
      command:
        - sleep
        - infinity
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ml
  labels:
    name: svc-ml
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: notebook
    - port: 6006
      name: tensorboard
  selector:
    name: pod-ml
